### ISSUE TITLE
Don't expose `SEPARATOR`

### ISSUE THREAD

**Issue by ewnd9** [ewnd9/anki-apkg-export#10]
https://github.com/ewnd9/anki-apkg-export/pull/9/commits/1416af518861d0f5a5efcf0c0f5db068bbe445d8

https://github.com/ewnd9/anki-apkg-export/pull/9/commits/41d7b86c50be30a919ee3d55c8ef4d8e21c40364

The first commit shouldn't have passed tests. // cc @vvscode

**Comment by vvscode** [comment]
@ewnd9  do you propose create test for it? 

it shouldn't break nothing but presentation of back side

**Comment by ewnd9** [comment]
I think it's better to don't import the separator and rather create it as a new variable in every test where it is needed

> it shouldn't break nothing but presentation of back side

I would say it's main responsibility of this module. (Correctly formatting cards)
