### ISSUE TITLE
Avoid using random / new Date() on generation

### ISSUE THREAD

**Issue by vvscode** [ewnd9/anki-apkg-export#11]
@ewnd9  What about  removing random generation / new Date during work? It makes harder to compare values and give no pros. We can just have incremented counter for each deck

Then we'll be able to compare decks with pre-generated in binary. And we'll be able to use sorting by id on queries

P.S. just note - why `export` when class import data into Anki deck?

**Comment by ewnd9** [comment]
> What about removing random generation / new Date during work? It makes harder to compare values and give no pros. We can just have incremented counter for each deck

That's a good question :+1: Got me thinking that we can simply mock `Date` and `Math.random` entirely. E.g. Run once and log every randomly generated value in tests, write an archive to the `fixtures` directory, then insert it as mocks.

> P.S. just note - why export when class import data into Anki deck?

Exporting data from JavaScript to an Anki `apkg` format archive.

**Comment by vvscode** [comment]
Is there any pros from random data inside exporter? We create each deck from scratch. So we can iterate from 1 up to. And it allow sort cards by import order ( right know we can't do it )

Also if in future we'll add ability to work with existing collections ( add new cards to existing decks ) random numbers can make a bad joke

**Comment by ewnd9** [comment]
> Is there any pros from random data inside exporter?

It's in the spec (http://decks.wikia.com/wiki/Anki_APKG_format_documentation)

> allow sort cards by import order ( right know we can't do it )

If it is missing in the spec, it's meaningless in a case of existing apps. Elaborate where do you want to sort cards, please.

> Also if in future we'll add ability to work with existing collections

I have a separate module in mind for import (haven't tested yet) https://github.com/davidey/anki-to-json

**Comment by vvscode** [comment]
it says `random` but I can even imagine cases which not covered with  incremented values

**Comment by ewnd9** [comment]
Elaborate where do you want to sort cards, please.

**Comment by vvscode** [comment]
https://github.com/ewnd9/anki-apkg-export/blob/d272b9290eb66489fa0a3bf896cb39e6db667ec3/test/test.js#L90 for example

also using random potentialy can generate conflict with identical ids for different rows

**Comment by ewnd9** [comment]
Do you think this is a shared problem between every Anki client / implementation?

**Comment by vvscode** [comment]
not sure. I'm as user never think about ids. But as for developer - using `random` numbers is strange

**Comment by ewnd9** [comment]
I recommend reaching `Anki` developers for discussing the purpose of `random` in DB or maintaining your own fork because I'm not intended to deviate from the spec.

**Comment by vvscode** [comment]
I understand. Maybe you can share link to main repo? Is it https://github.com/dae/anki ?

**Comment by ewnd9** [comment]
Yes

**Comment by ewnd9** [comment]
I reopened because I want to implement the random mock https://github.com/ewnd9/anki-apkg-export/issues/11#issuecomment-266392092 

Hope you will leave a note here on a dialog with the Anki developers

**Comment by vvscode** [comment]
https://anki.tenderapp.com/discussions/add-ons/8620-information-about-database-structuredetails

**Comment by vvscode** [comment]
and using random doesn't provide uniq

**Comment by ewnd9** [comment]
Spec was a lie :flushed: 

I made a little source code research, both the original Anki app and Ankidroid use timestamp + in loop increment for uniqueness, so a pull request to recreate a similar behavior is welcomed.

anki:

https://github.com/dae/anki/blob/24b451b0e4cfb50191e294052363a79f69f35c02/anki/notes.py#L17
https://github.com/dae/anki/blob/24b451b0e4cfb50191e294052363a79f69f35c02/anki/utils.py#L193-L200

ankidroid:

https://github.com/ankidroid/Anki-Android/blob/a6b58f2fc9a8fbf686fe6eaf2a42b76ed5d9a84f/AnkiDroid/src/main/java/com/ichi2/libanki/Note.java#L71
https://github.com/ankidroid/Anki-Android/blob/a6b58f2fc9a8fbf686fe6eaf2a42b76ed5d9a84f/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java#L385-L393

Also db structure description
https://github.com/ankidroid/Anki-Android/wiki/Database-Structure

wiki spec (random, lie)
http://decks.wikia.com/wiki/Anki_APKG_format_documentation

ruby (uses random)
https://github.com/albertzak/anki2/blob/master/lib/anki2.rb#L33

**Comment by vvscode** [comment]
Ok, thx

**Comment by ewnd9** [comment]
It's not ready to be closed, context: https://github.com/ewnd9/anki-apkg-export/pull/14#issuecomment-269115642

**Comment by vvscode** [comment]
https://github.com/ewnd9/anki-apkg-export/pull/15
