### ISSUE TITLE
Import of cards with tags is incomplete

### ISSUE THREAD

**Issue by hhzl** [ewnd9/anki-apkg-export#16]
Test https://github.com/hhzl/anki-apkg-export/commit/8397a6d52963ff26c646da6ceeedc513e53a5a6d has an example of importing cards with tags.

The tags are imported and show up in the Anki browser when the whole collection is selected. (Anki version 2.0.38 on Linux)
![screenshot from 2017-01-16 10 10 02](https://cloud.githubusercontent.com/assets/1112023/21978985/56919d38-dbdd-11e6-9a20-1b95b62310ff.png).

However then selecting a tag in the browser no entries are shown
![anki_export_tag_empty_in_browser_screenshot from 2017-01-16 10 10 37](https://cloud.githubusercontent.com/assets/1112023/21979026/78b3b9b4-dbdd-11e6-9e80-c0b27a26da30.png).

If create a new user in Anki  2.0.38 and import the CSV file the tags are fine.
![anki_import_csv_notes_test_screenshot from 2017-01-16 10 15 13](https://cloud.githubusercontent.com/assets/1112023/21979077/a93ba01a-dbdd-11e6-8d25-a28b4693d61c.png)

![anki_import_notes_with_tags_csv_screenshot from 2017-01-16 10 16 53](https://cloud.githubusercontent.com/assets/1112023/21979085/b5c40048-dbdd-11e6-98ef-395feed05a01.png)

It might be an issue with space in the tags field.  

The case which does not work
````
sqlite> select tags,flds,sfld from notes order by tags,sfld;
animal|cockder Hahn|cock
animal|cowdie Kuh|cow
animal|dogder Hund|dog
animal|goatdie Ziege|goat
animal|hendas Henne|hen
animal|hyenadie Hyäne|hyena
animal|lionder Löwe|lion
food|flourdas Mehl|flour
food|oildas Öl|oil
food|riceder Reis|rice
food|saltdas Salz|salt
food|waterdas Wasser|water
food fruit|bananadie Banane|banana
food fruit|lemondie Zitrone|lemon
food fruit|peardie Birne|pear
food vegetable|carrotdie Karotte|carrot
food vegetable|oniondie Zwiebel|onion
food vegetable|tomatodie Tomate|tomato
nature|a riverein Fluss|a river
nature|a treeein Baum|a tree
nature sky|one starein Stern|one star
nature sky|the moonder Mond|the moon
nature sky|the sundie Sonne|the sun
nature sky|three starsdrei Sterne|three stars
nature sky|two starszwei Sterne|two stars
sqlite> 
````

The case which works fine in the browser
````
sqlite> select tags,flds,sfld from notes order by tags,sfld;
 animal |cockder Hahn|cock
 animal |cowdie Kuh|cow
 animal |dogder Hund|dog
 animal |goatdie Ziege|goat
 animal |hendas Henne|hen
 animal |hyenadie Hyäne|hyena
 animal |lionder Löwe|lion
 food |flourdas Mehl|flour
 food |oildas Öl|oil
 food |riceder Reis|rice
 food |saltdas Salz|salt
 food |waterdas Wasser|water
 food fruit |bananadie Banane|banana
 food fruit |lemondie Zitrone|lemon
 food fruit |peardie Birne|pear
 food vegetable |carrotdie Karotte|carrot
 food vegetable |oniondie Zwiebel|onion
 food vegetable |tomatodie Tomate|tomato
 nature |a riverein Fluss|a river
 nature |a treeein Baum|a tree
 nature sky |one starein Stern|one star
 nature sky |the moonder Mond|the moon
 nature sky |the sundie Sonne|the sun
 nature sky |three starsdrei Sterne|three stars
 nature sky |two starszwei Sterne|two stars
sqlite> 
````

More tests needed to come up with a fix....

The next test will be to manually add a space after the tags field with an `update` statement and check if this solves the problem.

**Comment by hhzl** [comment]
The treatment of spaces in the `flags` field **is** an is an issue. And the number of tags plays a role.

After importing `output.apkg` in Anki the function `Check database...` in menu `Tools` has to be called.

**Comment by hhzl** [comment]
Another test https://github.com/hhzl/anki-apkg-export/commit/bfae507560371114cfda22f57577d02b1747c53b with an addition tag `word` added to all the cards.

**Result**
Still only partial lists of words for a specific tag in Anki browse mode.

After adding a space manually after each tag line in Anki browse mode clicking on a tag to display words works fine. 

**Note**
The process which creates `output.apkg` sorts  the tags are alphabetically.

**Comment by ewnd9** [comment]
Thank you :tada: Such elaborate reports are much appreciated :+1:
