### ISSUE TITLE
Can't pass APP_ENV to project, built with create-react-app

### ISSUE THREAD

**Issue by yakhinvadim** [ewnd9/anki-apkg-export#18]
Hi!
Thank you for this project. I'd like to use it in my web app [longman-to-anki](https://github.com/yakhinvadim/longman-to-anki) to generate anki deck on client side. Unfortunately, my stack doesn't allow me to pass APP_ENV to my app.

I'm using [create-react-app](https://github.com/facebookincubator/create-react-app), where all build scripts are hidden, so I don't have access to webpack config.
Create-react-app allows to use environment variables, but only as long, as their name starts with REACT_APP_ (more about it [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables)), so I can't create variable APP_ENV.

Is there any way environment could be inferred without passing environment variable?
Maybe, by checking if there is `window` object presented? If yes, I'd be glad to send a PR.
If no, do you see any way I can pass it to my project? Maybe I'm missing something.

**Comment by ewnd9** [comment]
Yep, window object would be fine. PR is welcomed :+1:

I didn't pay thorough attention to this aspect and just moved logic to a separate file so people with alternative bundlers (e.g. `browserify`) could require it directly `require('anki-apkg-export/dist/exporter`)

**Comment by yakhinvadim** [comment]
Great! I've made a PR #20.
