### ISSUE TITLE
Back card side doesn't have front side repeated

### ISSUE THREAD

**Issue by yakhinvadim** [ewnd9/anki-apkg-export#24]
Hi, it's me again :)
After last changes, everything works great, thanks! Apkg file is generated and successfully imported by Anki.
But cards' back side doesn't look as expected.

I looked into anki manual and found this: (https://apps.ankiweb.net/docs/manual.html#basic-templates)
> The default back template will look something like this:
> `{{FrontSide}}`
> `<hr id=answer>`
> `{{Back}}`

But cards, generated by anki-apkg-export, has this template:
> `{{Back}}`

Deck templates could be changed in anki settings, but I don't think users should do it manually.
IMO, it would be more convenient for users, if generated decks had default templates. Here's an example of what it looks like: 
![](http://yourawesomememory.com/images/anki-card-grade.jpg)

What do you think?

**Comment by ewnd9** [comment]
Seems fine :+1: I'm going to find the relevant code in AnkiDroid and the desktop client to refer to and then change it.
