### ISSUE TITLE
Difficulties with installing anki-apkg-export

### ISSUE THREAD

**Issue by deignouze** [ewnd9/anki-apkg-export#26]
Hello and thanks for this nice library.

I am a beginner in node NPM, webpack etc..... I read your documentation but really struggle to understand how to install and run your library. I am really confused on how to install the different dependencies and how to do the call to all of these scripts from my webpage. 

I simply want to reproduice on my website the sample application of https://ewnd9.com/anki-apkg-export-app/. 

Could you please add a little bit more information about the required steps to install/configure the required tools and libraries?

It would help a lot, thanks!

**Comment by ewnd9** [comment]
Hi. `anki-apkg-export-app` is on GitHub, in order to build it locally you need to do the following:

```sh
$ git clone https://github.com/ewnd9/anki-apkg-export-app.git
$ npm install
$ npm run build
```

After this, `dist` directory will contain the final sources.

> I am really confused on how to install the different dependencies

There is a ton of tutorials on npm/webpack/frontend development. I'm afraid I can't help you

**Comment by deignouze** [comment]
Thank you for your instructions, I will try again following them
