### ISSUE TITLE
Does it support tags? other anki features?

### ISSUE THREAD

**Issue by vvscode** [ewnd9/anki-apkg-export#4]
Hi. Can you share info about full anki card format? It there any information about adding media into cards ?

I'm interesting how you see adding tags in existing api ? Special format for text files, or use directory name as tags ( like `some/sub/dir1/file.txt` => tags `['some', 'sub', 'dir1']` )

**Comment by ewnd9** [comment]
Hi. I've updated README with examples links (media is supported, yes) and the `apkg` documentation reference. 

> Special format for text files, or use directory name as tags ( like some/sub/dir1/file.txt => tags ['some', 'sub', 'dir1'] )

Perhaps it is in the scope of https://github.com/ewnd9/anki-apkg-export-cli ? 

Your structure seems fine, although `type1-type2-type3.txt` looks better for me if a list of files fit in on the screen without scrolling

**Comment by ewnd9** [comment]
Looking at the original gem sources (https://github.com/albertzak/anki2/blob/5eb49e82309457cf24e1469535784c5ca900c639/lib/anki2.rb) this is the line which is responsible for tags representation — https://github.com/ewnd9/anki-apkg-export/blob/master/src/index.js#L97 Tags should be delimited by 1 white space character

**Comment by vvscode** [comment]
@ewnd9  I agree that logic for searching/parsing tags / additional fields it's in scope of cli tool. Is PR for ability to use additional fields in `addCard` welcome?

**Comment by ewnd9** [comment]
@vvscode 

![](http://i.giphy.com/AD2uIPYVqszdK.gif)

**Comment by vvscode** [comment]
Thus tags stored as single string with space delimiter -- for multiwords tags we can replace spaces with `\u160` ( it looks like space ) inside multiword tags

**Comment by vvscode** [comment]
can be closed, suppose
